Amigoz event-portal/SCM/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from scmapp import views

urlpatterns = [
    path('',views.home),
    # path(r'^/',views.index,name='index'),
    path('scm/',include('scmapp.urls')),
    path('admin/', admin.site.urls),
    #path('send/',send)
]

Amigoz event-portal/scmapp/urls.py
from django.conf.urls import url
from scmapp import views
from django import contrib
from django.urls import include
app_name = 'scmapp'

urlpatterns = [
    url(r'^registration', views.index),
    url(r'^user_home/', views.user_home),
    url(r'^test', views.test, name='test'),
    url(r'^login_user', views.login_user, name='login_user'),
    url(r'^admission',views.admission, name='admission'),
    url(r'^upcoming',views.upcoming, name='upcoming'),

    #url(r'^login_user', include("django.contrib.auth.urls"), name='login_user'),

    url(r'^admin_login', views.admin_login, name='admin_login'),
    url(r'^login_admin', views.login_admin, name='login_admin'),

    url(r'^admin_home', views.admin_home, name='admin_home'),
    url(r'^user_home', views.user_home, name='user_home'),

    url(r'^user_event', views.user_event, name='user_event'),
    url(r'^ground_booking', views.ground_booking, name='ground_booking'),
    url(r'^db_ground_booking', views.db_ground_booking, name='db_ground_booking'),

    url(r'^admin_booking', views.admin_booking, name='admin_booking'),
    url(r'^admin_event', views.admin_event, name='admin_event'),

    url(r'^update_event/(?P<id>\d+)/$', views.update_event, name='update_event'),
    url(r'^db_update_event/(?P<id>\d+)/$', views.db_update_event, name='db_update_event'),
    url(r'^db_delete_event/(?P<id>\d+)/$', views.db_delete_event, name='db_delete_event'),

    url(r'^add_event', views.add_event, name='add_event'),
    url(r'^db_add_event', views.db_add_event, name='db_add_event'),

    url(r'^user_logout', views.user_logout, name='user_logout'),
    url(r'^admin_logout', views.admin_logout, name='admin_logout'),

]

Amigoz event-portal/templates/add_event.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Add Event</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/add_event.css' %}">
</head>
<body class="bg-primary">
<div class="container-fluid header text-center bg-danger">
<h1 style="color: white">Event Details</h1>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 box bg-danger">
     <center><h1 style="color: white ,background-color:black, margin-right: 30px;"> Add Event</h1></center>

      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="inputbox">
            <form action="{% url 'scmapp:db_add_event' %}" method="post">
              {% csrf_token %}
              Name of event<br>
              <input type="text" name="name" autocomplete="off" required><br>

              Date<br>
              <input type="date" name="date" autocomplete="off" required><br>

              Time<br>
              <input type="time" name="time" required>

              Duration(hours)<br>
              <input type="number" name="duration" autocomplete="off" required>

              <div class="footer">
                <input type="reset" value="Reset" name="submit">
                <input type="submit" value="Add" name="submit">
              </div>

            </form>
          </div>
        </div>
      </div>
      <a href="{% url 'scmapp:admin_event' %}" class="btn btn-primary" style="color: white;">Back</a>
    </div>
  </div>
</div>

</body>
</html>

Amigoz event-portal/templates/admin_event.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Events</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/admin_event.css' %}">
</head>
<body class="bg-primary">
<div class="container-fluid header text-center">
  <h1 class="bg-danger" style="color: white;">Manage Events</h1>
</div>

<div class="container box bg-success">
  <a href="add_event.php"><button style="float:right;">Add Event</button></a>
  <h1 style="color: white;">Event Details</h1><br>
  
  <span style="font-size:16px;">{{ status }}</span>

  <table>
    <tr class="bg-primary" style="color: white;">
      <td>No</td>
      <td>Event name</td>
      <td>Date</td>
      <td>Time</td>
      <td>Duration</td>
      <td>Update</td>
      <td>Delete</td>
    </tr>

    {% for e in event %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ e.name}}</td>
        <td>{{ e.date }}</td>
        <td>{{ e.time }}</td>
        <td>{{ e.duration }}</td>
        <td><a href="{% url 'scmapp:update_event' id=e.eid %}">Update</a></td>
        <td><a href="{% url 'scmapp:db_delete_event' id=e.eid %}">Delete</a></td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="7" align="center">No Events</td>
      </tr>
    {% endfor %}

  </table>

  <div class="footer">
    <a href="{% url 'scmapp:admin_home' %}"><button>Back</button></a>
  </div>

</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>
</html>

Amigoz event-portal/templates/admin_home.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Events Management System</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>

<body class="bg-primary" style="color:white">
<div class="container-fluid header text-center bg-danger">
 <h1>CHRIST COLLEGE<BR> Event Management System</h1>
  Welcome {{ name }}
  <a href="{% url 'scmapp:admin_logout' %}" style="font-size:20; color: white;">Logout</a>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <a href="{% url 'scmapp:admin_event' %}">
      <div class="card bg-danger">
        <img src="{% static 'res/event.jpeg' %}">
        <div class="card-title text-center" style="color: white;">Events</div>
      </div>
      </a>
    </div>

    <div class="col-lg-6">
      <a href="{% url 'scmapp:admin_booking' %}">
      <div class="card bg-danger">
        <img src="{% static 'res/volley.jpg' %}" style="height:312px;">
        <div class="card-title text-center" style="color: white;">Events Booking</div>
      </div>
      </a>
    </div>

  </div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>
</html>

Amigoz event-portal/templates/ground_booking.html
<!DOCTYPE html>
{% load static %}

<html xmlns="http://www.w3.org/1999/html">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Events Booking</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/add_event.css' %}">
</head>
<body class="bg-primary">
<div class="container-fluid header text-center bg-success">
  <h1 style="color: white;">Events Booking</h1>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 box bg-success">
      <center><h2 class="bg-danger" style="color: white; margin-right:30px; ">Events Booking Details</h2></center>
      <span style="font-size:18px">{{ status }}</span>

      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="inputbox">
            <form action="{% url 'scmapp:db_ground_booking' %}" method="post">
              {% csrf_token %}
               Name of event<br>
              <input type="text" name="name" autocomplete="off" required><br>

<!--              Mobile<br>-->
<!--              <input type="text" name="mobile" minlength="10" maxlength="10" autocomplete="off" pattern="[6-9]{1}[0-9]{9}" title="Numbers only" required><br>-->

              Date<br>
              <input type="date" name="date" min="{{ date }}" autocomplete="off" required><br>

              Time<br>
              <input type="time" name="time" min="06:00" max="18:00" required>

              <div class="footer">
                <input type="reset" value="Reset" name="submit">
                <input type="submit" value="Book" name="submit">
              </div>

            </form>
          </div>
        </div>
      </div>
      <a href="{% url 'scmapp:user_home' %}" style="color: white;">Back</a>
    </div>
  </div>
</div>

</body>



</html>

Amigoz event-portal/templates/registration.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Registration| Welcome</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/registration2.css' %}">
  <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</head>
<body style="background-image: url('/static/res/grey.jpeg');
  background-repeat: no-repeat;
  background-size: 100% 100%;">

<div ><center>
  <h1 style="color: white"><b>CHRIST COLLEGE</b><BR> <i>Events Management System</i></h1></center>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-0 btn-bar" onclick="navigation(event)">
      <a href="#" class="myactive" id="registration">Registration</a>
      <a href="#" class=""  id="login">Login</a>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 box " style="display:block; background-image: url('/static/res/sky.jpeg');
  background-repeat: no-repeat;
  background-size: 100% 100%;">
<!--      <div class="col-lg-6 box bg-danger" style="display:block;">-->
      <!-- <span style="font-size:26px;">Registration</span> -->
      <center><h1  style="color: white; margin-right: 30px;"> Registration</h1></center>
      <span style="font-size:18px;">{{ status }}</span>

      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="inputbox">
            <form action="{% url 'scmapp:test' %}" method="post">
              {% csrf_token %}
              <p style="color:white;"> Username<br>
                <input type="text" name="uname" autocomplete="off" required><br>

              E-Mail<br>
                <input type="text" name="email" autocomplete="off" required><br>

                Mobile<br>
              <input type="text" name="mobile" minlength="10" maxlength="10" autocomplete="off" pattern="[6-9]{1}[0-9]{9}" title="Numbers only" required><br>


              Gender<br>
              <input type="radio" name="gender" value="Male"> Male
              <input type="radio" name="gender" value="Female"> Female<br>

              Password<br>
              <input type="password" name="password" minlength="8" autocomplete="off" required><br>

              Re-enter Password<br>
                <input type="password" name="repassword" minlength="8" autocomplete="off" required></p>

              <input type="submit" value="Submit" name="submit" style="margin:0 25% 0 25%;">
            </form>
          </div>
        </div>
    </div>
<!--    <a href="#" onclick="navigation(event)" id="loginLink" style="color: white;">Already registered? Login</a>-->

    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 loginBox " style="display:none; background-image: url('/static/res/sky.jpeg');
  background-repeat: no-repeat;
  background-size: 100% 100%;">
      <center><h1  style="color: white; margin-right: 30px;">Login</h1></center>
      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="inputBox" style="font-size:18px;">
            <form action="{% url 'scmapp:login_user' %}" method="post">
              {% csrf_token %}
              <p style="color:white;">Username<br>
              <input type="text" name="name" autocomplete="off" required><br>

              Password<br>
                <input type="password" name="password" minlength="8" autocomplete="off" required></p>

              <input type="submit" value="Login" name="login" style="margin:0 25% 0 25%;">
            </form>
          </div>
        </div>
      </div>

<!--      <a href="#" onclick="navigation(event)" id="regLink" style="color: white;">Not a registered user? Register</a>-->
      <center ><BR><p style="color:white;">Not a registered user?</p>

      <a href="/scm/registration" onclick="navigation(event)" id="regLink" style="color: white">
        <input type="submit" value="Register" name="Register" style="margin:0 25% 0 25%"></a></center>


    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>

</html>

Amigoz event-portal/templates/update_event.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Update Event</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/add_event.css' %}">
</head>
<body class="bg-success">
<div class="container-fluid header text-center">
  <h1 class="bg-primary" style="color: white;">Manage Event</h1>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 box bg-danger">
      <center><h1 class="bg-success" style="color: white; margin-right: 30px;">Update Event</h1></center>

      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="inputbox">
            <form action="{% url 'scmapp:db_update_event' id=event.eid %}" method="post">
              {% csrf_token %}
              Name of event<br>
              <input type="text" name="name" autocomplete="off" value="{{ event.name }}" required><br>

              Date<br>
              <input type="date" name="date" autocomplete="off" value="{{ event.date }}" required><br>

              Time<br>
              <input type="time" name="time" value="{{ event.time }}" min="06:00" max="18:00" required><br>

              Duration(hours)<br>
              <input type="number" name="duration" autocomplete="off" value="{{ event.duration }}" min="1" required>

              <div class="footer">
                <input type="reset" value="Reset" name="submit">
                <input type="submit" value="Update" name="submit">
              </div>

            </form>
          </div>
        </div>
      </div>
      <a href="{% url 'scmapp:admin_event' %}" class="btn btn-primary">Back</a>
    </div>
  </div>
</div>

</body>

</html>

Amigoz event-portal/templates/user_event.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>CHRIST COLLEGE Events</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/admin_event.css' %}">
</head>
<body style="background-image: url('/static/res/grey.jpeg');
  background-repeat: no-repeat;
  background-size: 100% 100%;">
<div class="container-fluid header text-center ">
 <h2 style="color: white;">CHRIST COLLEGE </h2>
  <h3 style="color: white;"> Events</h3>
</div>

<div class="container box " style="background:#c3073f"><center>
  <h2  style="color: white;">Event Details</h2></center>

  <table>
    <tr style="color: white; background-color:black;">
      <td>No</td>
      <td>Event name</td>
      <td>Date</td>
      <td>Time</td>
      <td>Duration(hours)</td>
      <td>Register</td>
    </tr>

    {% for e in event %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ e.name}}</td>
        <td>{{ e.date }}</td>
        <td>{{ e.time }}</td>
        <td>{{ e.duration }}</td>
        <td>
          <form action="{% url 'scmapp:db_ground_booking' %}" method="post">
              {% csrf_token %}
            <input type="submit" value="Book" name="submit">
<!--            <input type="submit" value>-->

            <input type="hidden" value={{ e.name }} name="name">
<!--            <input type="hidden" value={{ e.date }} name="date"  >-->
            <input type="hidden" value={{ e.time }} name="time" >

          </form>
        </td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="5" align="center">No events</td>
      </tr>
    {% endfor %}

  </table>

  <div class="footer">
    <a href="{% url 'scmapp:user_home' %}"><button>Back</button></a>
  </div>

</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>
</html>

Amigoz event-portal/templates/user_home.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Event Management System</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/index1.css' %}">
   <style>
      .my-block {
        text-align: center;
        vertical-align:middle;

      }
      .button {
        display: inline-block;
        border-radius: 10px;
        background-color: #d39e00;
        border: none;
        color: #FFFFFF;
        text-align: center;
        font-size: 20px;
        padding: 10px;
        width: 200px;
        transition: all 0.5s;
        cursor: pointer;
        margin: 5px;
      }
      .button span {
        cursor: pointer;
        display: inline-block;
        position: relative;
        transition: 0.5s;
      }
      .button span:after {
        content: '\00bb';
        position: absolute;
        opacity: 0;
        top: 0;
        right: -20px;
        transition: 0.5s;
      }
      .button:hover span {
        padding-right: 25px;
      }
      .button:hover span:after {
        opacity: 1;
        right: 0;
      }
  </style>
</head>

<body style="background-image: url('/static/res/yellow.jpeg');background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: 100% 100%;">
<div class="container-fluid header text-center ">
  <h1 style="color: black;font-weight: 700;"><b>CHRIST COLLEGE</b> <BR><i>Events Management System</i></h1>
  <h3 style="color: black;font-weight: 600;"> <i>Welcome {{ name }} </i></h3>
   <div class="my-block">
            <a href="{% url 'scmapp:user_logout' %}"><button class="button" ><span>LOGOUT</span></button></a>
     </div>
  <span style="font-size:24px">{{ status }}</span>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <a href="{% url 'scmapp:user_event' %}">
      <div class="card " style="background-color:white;">
        <img src="{% static 'res/basketball.jpeg' %}">
        <div class="card-title text-center" style="color: black;">Events</div>
      </div>
      </a>
    </div>

<!--    <div class="col-lg-6">-->
<!--      <a href="{% url 'scmapp:ground_booking' %}">-->
<!--      <div class="card ">-->
<!--        <img src="{% static 'res/football.jpeg' %}" style="height:460px;">-->
<!--        <div class="card-title text-center" style="color: black;">Events Booking</div>-->
<!--      </div>-->
<!--      </a>-->
<!--    </div>-->

    <div class="col-lg-6">
      <a href="{% url 'scmapp:admission' %}">
      <div class="card " >
        <img src="{% static 'res/colorball.jpeg' %}" style="height:460px;">
        <div class="card-title text-center" style="color: black;">Registered Students details</div>
      </div>
      </a>
    </div>


    <div class="col-lg-6"><center>
      <a href="{% url 'scmapp:upcoming' %}">
      <div class="cards " style="background-color:black;">
        <img src="{% static 'res/upcoming1.jpeg' %}" style="height:460px;width:1000px;">
        <div class="cards-title text-center" style="color: black;">  </div>
      </div>
      </a></center>
    </div>


  </div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>
</html>